/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVerifyRouteImport } from './routes/_app.verify'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppDistributionRouteImport } from './routes/_app.distribution'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBeneficiariesRouteImport } from './routes/_app.beneficiaries'
import { Route as AppCardsIndexRouteImport } from './routes/_app.cards.index'
import { Route as AppCardsIdRouteImport } from './routes/_app.cards.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVerifyRoute = AppVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributionRoute = AppDistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBeneficiariesRoute = AppBeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsIndexRoute = AppCardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsIdRoute = AppCardsIdRouteImport.update({
  id: '/cards/$id',
  path: '/cards/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beneficiaries': typeof AppBeneficiariesRoute
  '/dashboard': typeof AppDashboardRoute
  '/distribution': typeof AppDistributionRoute
  '/reports': typeof AppReportsRoute
  '/verify': typeof AppVerifyRoute
  '/cards/$id': typeof AppCardsIdRoute
  '/cards/': typeof AppCardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beneficiaries': typeof AppBeneficiariesRoute
  '/dashboard': typeof AppDashboardRoute
  '/distribution': typeof AppDistributionRoute
  '/reports': typeof AppReportsRoute
  '/verify': typeof AppVerifyRoute
  '/cards/$id': typeof AppCardsIdRoute
  '/cards': typeof AppCardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/beneficiaries': typeof AppBeneficiariesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/distribution': typeof AppDistributionRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/verify': typeof AppVerifyRoute
  '/_app/cards/$id': typeof AppCardsIdRoute
  '/_app/cards/': typeof AppCardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beneficiaries'
    | '/dashboard'
    | '/distribution'
    | '/reports'
    | '/verify'
    | '/cards/$id'
    | '/cards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beneficiaries'
    | '/dashboard'
    | '/distribution'
    | '/reports'
    | '/verify'
    | '/cards/$id'
    | '/cards'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/beneficiaries'
    | '/_app/dashboard'
    | '/_app/distribution'
    | '/_app/reports'
    | '/_app/verify'
    | '/_app/cards/$id'
    | '/_app/cards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/verify': {
      id: '/_app/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AppVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/distribution': {
      id: '/_app/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof AppDistributionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beneficiaries': {
      id: '/_app/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof AppBeneficiariesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cards/': {
      id: '/_app/cards/'
      path: '/cards'
      fullPath: '/cards/'
      preLoaderRoute: typeof AppCardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cards/$id': {
      id: '/_app/cards/$id'
      path: '/cards/$id'
      fullPath: '/cards/$id'
      preLoaderRoute: typeof AppCardsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBeneficiariesRoute: typeof AppBeneficiariesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDistributionRoute: typeof AppDistributionRoute
  AppReportsRoute: typeof AppReportsRoute
  AppVerifyRoute: typeof AppVerifyRoute
  AppCardsIdRoute: typeof AppCardsIdRoute
  AppCardsIndexRoute: typeof AppCardsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBeneficiariesRoute: AppBeneficiariesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDistributionRoute: AppDistributionRoute,
  AppReportsRoute: AppReportsRoute,
  AppVerifyRoute: AppVerifyRoute,
  AppCardsIdRoute: AppCardsIdRoute,
  AppCardsIndexRoute: AppCardsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
